BEGIN;
INSERT INTO categories (id, value, slug) VALUES
    (gen_random_uuid(), 'Электроника и периферия', 'electronics-and-peripherals'),
    (gen_random_uuid(), 'Бытовая техника и уход', 'home-appliances-and-personal-care'),
    (gen_random_uuid(), 'Одежда, обувь и аксессуары', 'clothing-footwear-and-accessories'),
    (gen_random_uuid(), 'Мебель и домашний текстиль', 'furniture-and-home-textiles'),
    (gen_random_uuid(), 'Ремонт и инструменты', 'repair-and-tools'),
    (gen_random_uuid(), 'Зоотовары', 'pet-supplies'),
    (gen_random_uuid(), 'Детские товары', 'baby-and-kids-products'),
    (gen_random_uuid(), 'Спорт и активный отдых', 'sports-and-outdoors');
COMMIT;

BEGIN;
INSERT INTO categories (id, value, slug, parent_id) VALUES
    -- Электроника и периферия
    (gen_random_uuid(), 'Смартфоны', 'smartphones', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Ноутбуки', 'laptops', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Наушники', 'headphones', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Часы', 'watches', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Планшеты', 'tablets', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Клавиатуры', 'keyboards', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Мыши', 'mice', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Мониторы', 'monitors', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Принтеры', 'printers', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Камеры', 'cameras', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Объективы', 'lenses', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Игровые приставки', 'gaming-consoles', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Игры', 'games', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Телевизоры', 'televisions', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),
    (gen_random_uuid(), 'Проекторы', 'projectors', (SELECT id FROM categories WHERE slug = 'electronics-and-peripherals')),

    -- Бытовая техника и уход
    (gen_random_uuid(), 'Холодильники', 'refrigerators', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Плиты', 'stoves', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Микроволновки', 'microwaves', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Чайники', 'kettles', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Кофемашины', 'coffee-machines', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Блендеры', 'blenders', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Тостеры', 'toasters', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Пылесосы', 'vacuum-cleaners', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Утюги', 'irons', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Фены', 'hair-dryers', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Эпиляторы', 'epilators', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Бритвы', 'shavers', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Зубные щетки', 'toothbrushes', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Весы', 'scales', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),
    (gen_random_uuid(), 'Кондиционеры', 'air-conditioners', (SELECT id FROM categories WHERE slug = 'home-appliances-and-personal-care')),

    -- Одежда, обувь и аксессуары
    (gen_random_uuid(), 'Платья', 'dresses', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Рубашки', 'shirts', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Джинсы', 'jeans', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Брюки', 'trousers', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Юбки', 'skirts', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Костюмы', 'suits', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Пальто', 'coats', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Куртки', 'jackets', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Свитера', 'sweaters', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Футболки', 't-shirts', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Шорты', 'shorts', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Нижнее белье', 'underwear', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Носки', 'socks', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Кроссовки', 'sneakers', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Туфли', 'shoes', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Ботинки', 'boots', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Сандалии', 'sandals', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Сумки', 'bags', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Рюкзаки', 'backpacks', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Кошельки', 'wallets', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Ремни', 'belts', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Шляпы', 'hats', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Очки', 'glasses', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Серьги', 'earrings', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Кольца', 'rings', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),
    (gen_random_uuid(), 'Браслеты', 'bracelets', (SELECT id FROM categories WHERE slug = 'clothing-footwear-and-accessories')),

    -- Мебель и домашний текстиль
    (gen_random_uuid(), 'Кровати', 'beds', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Диваны', 'sofas', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Столы', 'tables', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Стулья', 'chairs', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Шкафы', 'wardrobes', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Комоды', 'dressers', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Полки', 'shelves', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Зеркала', 'mirrors', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Матрасы', 'mattresses', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Постельное белье', 'bed-linen', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Полотенца', 'towels', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Шторы', 'curtains', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Посуда', 'tableware', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Сковородки', 'frying-pans', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Кастрюли', 'pots', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),
    (gen_random_uuid(), 'Ножи', 'knives', (SELECT id FROM categories WHERE slug = 'furniture-and-home-textiles')),

    -- Ремонт и инструменты
    (gen_random_uuid(), 'Инструменты', 'tools', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Дрели', 'drills', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Шуруповерты', 'screwdrivers', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Молотки', 'hammers', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Обои', 'wallpaper', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Краски', 'paints', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Ламинат', 'laminate', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),
    (gen_random_uuid(), 'Плитка', 'tiles', (SELECT id FROM categories WHERE slug = 'repair-and-tools')),

    -- Зоотовары
    (gen_random_uuid(), 'Корм для кошек', 'cat-food', (SELECT id FROM categories WHERE slug = 'pet-supplies')),
    (gen_random_uuid(), 'Корм для собак', 'dog-food', (SELECT id FROM categories WHERE slug = 'pet-supplies')),
    (gen_random_uuid(), 'Аквариумы', 'aquariums', (SELECT id FROM categories WHERE slug = 'pet-supplies')),
    (gen_random_uuid(), 'Клетки', 'cages', (SELECT id FROM categories WHERE slug = 'pet-supplies')),
    (gen_random_uuid(), 'Игрушки для животных', 'pet-toys', (SELECT id FROM categories WHERE slug = 'pet-supplies')),

    -- Детские товары
    (gen_random_uuid(), 'Детское питание', 'baby-food', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),
    (gen_random_uuid(), 'Подгузники', 'diapers', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),
    (gen_random_uuid(), 'Коляски', 'strollers', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),
    (gen_random_uuid(), 'Автокресла', 'car-seats', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),
    (gen_random_uuid(), 'Конструкторы', 'building-sets', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),
    (gen_random_uuid(), 'Куклы', 'dolls', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),
    (gen_random_uuid(), 'Машинки', 'toy-cars', (SELECT id FROM categories WHERE slug = 'baby-and-kids-products')),

    -- Спорт и активный отдых
    (gen_random_uuid(), 'Спортивная одежда', 'sportswear', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Мячи', 'balls', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Гантели', 'dumbbells', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Йога', 'yoga', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Туризм', 'tourism', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Палатки', 'tents', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Спальники', 'sleeping-bags', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors')),
    (gen_random_uuid(), 'Фонари', 'flashlights', (SELECT id FROM categories WHERE slug = 'sports-and-outdoors'));
COMMIT;