# Generated by Django 6.0.5 on 2026-05-25 11:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +79999999999', regex='^\\+?[0-9]{10,15}$')])),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('slug', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, null=True)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, null=True)),
                ('seo_description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('slug', models.CharField()),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CategorySEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('CARD', 'Card'), ('SBP', 'Sbp'), ('WALLET', 'Wallet')])),
                ('card_last4', models.TextField(max_length=4, validators=[django.core.validators.RegexValidator(message='Нужно ввести последние 4 цифры номера карты', regex='^[0-9]{4}$')])),
                ('card_brand', models.TextField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('MIR', 'Mir')])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField()),
                ('status', models.TextField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('ASSEMBLING', 'Assembling'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('CANCEL_PENDING', 'Cancel Pending')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.paymentmethod')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
                ('name', models.CharField()),
                ('sku_code', models.CharField(blank=True, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image_url', models.CharField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='src.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
