# Generated by Django 6.0.4 on 2026-04-24 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('slug', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, null=True)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, null=True)),
                ('seo_description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('slug', models.CharField()),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CategorySEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('name', models.CharField()),
            ],
        ),
    ]
