# Generated by Django 6.0.5 on 2026-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoperations',
            name='type',
            field=models.TextField(choices=[('CREATE', 'Create'), ('CANCEL', 'Cancel'), ('FULFILL', 'Fulfill')]),
        ),
    ]
