# Generated by Django 6.0.5 on 2026-05-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_address_buyer_paymentmethod_buyer_orderoperations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderoperations',
            old_name='id',
            new_name='idempotency_key',
        ),
    ]
