# Generated by Django 6.0.5 on 2026-06-11 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_orderoperations_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorites',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'product_id'), name='unique_user_product')],
            },
        ),
    ]
