# Generated by Django 6.0.5 on 2026-06-11 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('events', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_subscriptions',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'product_id'), name='unique_user_product_subscription')],
            },
        ),
    ]
