# Generated by Django 6.0.5 on 2026-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_productsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_events',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
