# Generated by Django 6.0.5 on 2026-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('ASSEMBLING', 'Assembling'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('CANCEL_PENDING', 'Cancel Pending')]),
        ),
    ]
