# Generated by Django 6.0.5 on 2026-05-31 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedFulfillAttempts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'failed_fulfill_attempts',
            },
        ),
    ]
